### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by URL42** [EngineersNeedArt/SystemSix#1]
Not an issue, but I didn't see another way to ask questions. I love the look of your SystemSix project. It is very nostalgic for me as my first computer experiences were with this version of an Apple. I'm new to programming / micro computing, so forgive my basic questions. I was wondering if it matters what size of screen (other than for the case), or can I use a bigger version of the screen (7.5") that I already have? Also, is there a way to show more calendar items, or have the screen refresh more than once per day?  Thanks!!

**Comment by EngineersNeedArt** [comment]
You can use another size screen. You will have to make changes in the code however, I believe.
You'll need to know the pixel width/height of your display.

In `systemsix.py` look for this line:
`    ink_image = Image.open(os.path.join(ARTWORK_DIR, "blank.bmp"))`

Some things to note. `ink_image` is the "canvas" that everything is drawn on. It just so happens that it is a blank image (not surprising since it is opening an image named `"blank.bmp"`) that is the exact size of my e-ink display.

Now that I know a bit more about creating images in Python, I should probably replace that line of code with this line:
`    ink_image = Image.new(mode = "RGBA", size = (648, 480), color='white')`

That would allow me to get rid of the `"blank.bmp"` asset and be more clear as to what it does: creates a blank (white) image with the size 648 x 480 pixels (and red, green, blue + alpha for the pixel representation).

I would suggest you do this. But of course replace (648, 480) with the pixel dimensions of your display.

**Comment by EngineersNeedArt** [comment]
Also note this line in `systemsix.py`:

`USE_EINK_DISPLAY = True  # Set to False to (test) build on a machine without an e-ink display.`

Definitely try setting this to `False` first. If you do this you will not need an e-ink display at all in order to build, test the project.

This:
`USE_EINK_DISPLAY = False`

This will also allow you to quickly move images around, etc. and see your changes quickly (e-ink displays can be slow to draw).

**Comment by EngineersNeedArt** [comment]
You can show more than 6 calendar items.

In `systemsix.py`, look for this line: `event_list = get_events(6)`

You can guess what to do.

**Comment by EngineersNeedArt** [comment]
**SystemSix** considers an update every hour. See this line in `systemsix.py`:

`    schedule.every().hour.at("05:00").do(update)`

This says, every hour (well, 5 minutes after the hour), call the `update()` function.

So you see it already checks in every hour.

To your question though, look at `update()`. It calls `update_or_start()`. Okay, look at `update_or_start()`.

Without going deep into the weeds, notice the line: `do_update_display = False`

Look further down to see when it is set to true. Only when `True` is the display redrawn. You could easily make changes here to have it update the display _every_ hour (every time `update_or_start()` is called).

**Comment by URL42** [comment]
Great! Thank you very much for the responses!
